Fix Timeout

diff --git a/.github/workflows/run.yaml b/.github/workflows/run.yaml
--- a/.github/workflows/run.yaml
+++ b/.github/workflows/run.yaml
@@ -29,8 +29,10 @@ jobs:
               ${{ runner.os }}-maven-
       - name: Package
         run: mvn clean install 
-      - name: Run
-        run: timeout 10 docker build --build-arg JAR_FILE=target/*.jar -t org/acme . && docker run -p 8080:8080 org/acme && code=$?;echo "Code = $code" && exit $code
+      - name: Run # Without timeout
+        run: docker build --build-arg JAR_FILE=target/*.jar -t org/acme . && docker run -p 8080:8080 org/acme && code=$?;echo "Code = $code" && exit $code
+      - name: Run # We add or so that return code is not none-zero which causes pipeline to fail
+        run: timeout 1  docker build --build-arg JAR_FILE=target/*.jar -t org/acme . && docker run -p 8080:8080 org/acme && code=$?;echo "Code = $code" && exit $code
 
 
 
